### PR TITLE
Approve without body

### PR DESCRIPTION
**Pull request by soehms**
This PR implements the requested changes of https://github.com/sagemath/sage/pull/36292#issuecomment-1734903660. 

Furthermore a couple of issues are fixed wich occur while testing it (see item 5. ... 9. in the header of https://github.com/sagemath/sage/pull/36292).

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

<a href="https://gitpod.io/#https://github.com/soehms/sage/pull/11"></a>

### CODE REVIEW

**Comment by kwankyu** [comment]
```
NFO:root:PR pull request #11 can be approved by kwankyu
Traceback (most recent call last):
  File "/home/runner/work/sage/sage/.github/sync_labels.py", line 913, in <module>
    gh.run(action, label=label, rev_state=rev_state)
  File "/home/runner/work/sage/sage/.github/sync_labels.py", line 785, in run
    self.on_label_add(label)
  File "/home/runner/work/sage/sage/.github/sync_labels.py", line 715, in on_label_add
    self.approve()
  File "/home/runner/work/sage/sage/.github/sync_labels.py", line 560, in approve
    self.review('--approve')
  File "/home/runner/work/sage/sage/.github/sync_labels.py", line 554, in review
    self.gh_cmd('review', arg)
TypeError: GhLabelSynchronizer.gh_cmd() missing 1 required positional argument: 'option'
Error: Process completed with exit code 1.
```

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by soehms** [comment]
> ```
> NFO:root:PR pull request #11 can be approved by kwankyu
> Traceback (most recent call last):
>   File "/home/runner/work/sage/sage/.github/sync_labels.py", line 913, in <module>
>     gh.run(action, label=label, rev_state=rev_state)
>   File "/home/runner/work/sage/sage/.github/sync_labels.py", line 785, in run
>     self.on_label_add(label)
>   File "/home/runner/work/sage/sage/.github/sync_labels.py", line 715, in on_label_add
>     self.approve()
>   File "/home/runner/work/sage/sage/.github/sync_labels.py", line 560, in approve
>     self.review('--approve')
>   File "/home/runner/work/sage/sage/.github/sync_labels.py", line 554, in review
>     self.gh_cmd('review', arg)
> TypeError: GhLabelSynchronizer.gh_cmd() missing 1 required positional argument: 'option'
> Error: Process completed with exit code 1.
> ```

I've fixed this. Can you try again?

**Review by kwankyu — CHANGES_REQUESTED** [review]
Let's see this work well.

**Comment by kwankyu** [comment]
In 
```
Label Sync Warning: Label s: positive review can not be added. Please use the GitHub review functionality
```
"can not" -> "cannot".

I don't know if this message is appropriate, forbidding manually adding "positive review".

People are already using "positive review" label as the primary way to express the decision to accept a PR. Release manager script is using it that way. 

"Approve" in github meaning is being understood as approval of one reviewer, not the final decision. 

I think we should not disrupt the practice. How about viewing "Approve" as a way to add "positive review" and allow adding (or removing) "positive review" manually.

**Review by kwankyu — APPROVED** [review]

**Comment by kwankyu** [comment]
I cannot add "positive review" because the bot "requested changes".

**Comment by kwankyu** [comment]
Instead of
```
Label Sync Warning: Label s: positive review cannot be added. Please use the GitHub review functionality
```
could be rephrased
```
Cannot add "s: positive review" label because there is a request for changes.
```
which sounds more human.

But this rejection is too restrictive. Someone might give "a request for changes" and forget about the PR.  Then other people cannot process the PR... (People do all kinds of erroneous acts.)

**Comment by soehms** [comment]
> Instead of
> 
> ```
> Label Sync Warning: Label s: positive review cannot be added. Please use the GitHub review functionality
> ```
> 
> could be rephrased
> 
> ```
> Cannot add "s: positive review" label because there is a request for changes.
> ```
> 
> which sounds more human.
> 
> But this rejection is too restrictive. Someone might give "a request for changes" and forget about the PR. Then other people cannot process the PR... (People do all kinds of erroneous acts.)

Thanks for testing! Not every reaction of the bot was expected. Therefore it was much more restrictive than intended. The following two issues occurred:


1. When you [approved the PR via GitHub review](https://github.com/soehms/sage/pull/11#pullrequestreview-1645784407), the `s: positive review` label should have been set. This failed because the bot couldn't establish your authentication (from the [log file](https://github.com/soehms/sage/actions/runs/6322763252/job/17168990655)):

```
DEBUG:root:Execute command: gh api -X GET -H "Accept: application/vnd.github+json" /orgs/sagemath/teams/triage/memberships/kwankyu 
gh: Not Found (HTTP 404)
INFO:root:User kwankyu is not a member of triage
```

If I do it in a bash shell the command just works:

```
gh api -X GET -H "Accept: application/vnd.github+json" /orgs/sagemath/teams/triage/memberships/kwankyu
{
  "state": "active",
  "role": "member",
  "url": "https://api.github.com/organizations/982721/team/7336698/memberships/kwankyu"
}
```

I think this is related to the issue I explained in the second paragraph of https://github.com/sagemath/sage/pull/36213#issue-1887191386: Since the bot is not a member of the SageMath organization (or Triage team in this case) it cannot see if someone else is a member as long as the membership is private.


2. Besides the list of individual reviews the GitHub CLI offers to query a `reviewDecision` which can be supported in a special case or not. In https://github.com/sagemath/trac-to-github/pull/187 (see the review https://github.com/sagemath/trac-to-github/pull/187#discussion_r1103566325 there)  @tobiasdiez already warned me that this is not reliable. But unfortunately I didn't expect the reliability being that worse. Thus, I still used it when supported. But now I see that it doesn't make sense even in that case.

In your test `reviewDecision` was set by the bot to `CHANGES_REQUESTED`. But it was not changed to `APPROVED` after you approved the PR. Because of that you could not add the `s: positive review` label [afterwards](https://github.com/soehms/sage/pull/11#event-10483637800) (from the [log file](https://github.com/soehms/sage/actions/runs/6322772214/job/17169017211)):

```
DEBUG:root:Execute command: gh pr view https://github.com/soehms/sage/pull/11 --json reviewDecision

INFO:root:Review decision for pull request #11: CHANGES_REQUESTED
INFO:root:PR pull request #11 doesn't have positve review (by decision)

INFO:root:Proper reviews after 2023-09-27T05:37:47Z for pull request #11: [{'id': 'PRR_kwDOI72C3M5iF8xa', 'author': {'login': 'github-actions'}, 'authorAssociation': 'NONE', 'body': '', 'submittedAt': '2023-09-27T06:52:19Z', 'includesCreatedEdit': False, 'reactionGroups': [], 'state': 'APPROVED', 'commit': {'oid': '1db7d1a74c8905b9b99b5580dae11b2ae7744456'}}, {'id': 'PRR_kwDOI72C3M5iF9Zp', 'author': {'login': 'github-actions'}, 'authorAssociation': 'NONE', 'body': '@kwankyu requested changes for this PR:\r\n\r\nWorking well.', 'submittedAt': '2023-09-27T06:54:01Z', 'includesCreatedEdit': False, 'reactionGroups': [], 'state': 'CHANGES_REQUESTED', 'commit': {'oid': '1db7d1a74c8905b9b99b5580dae11b2ae7744456'}}, {'id': 'PRR_kwDOI72C3M5iF-DH', 'author': {'login': 'kwankyu'}, 'authorAssociation': 'COLLABORATOR', 'body': "Let's see this work well.", 'submittedAt': '2023-09-27T06:55:46Z', 'includesCreatedEdit': False, 'reactionGroups': [], 'state': 'CHANGES_REQUESTED', 'commit': {'oid': '1db7d1a74c8905b9b99b5580dae11b2ae7744456'}}, {'id': 'PRR_kwDOI72C3M5iGK1X', 'author': {'login': 'kwankyu'}, 'authorAssociation': 'COLLABORATOR', 'body': '', 'submittedAt': '2023-09-27T07:27:52Z', 'includesCreatedEdit': False, 'reactionGroups': [], 'state': 'APPROVED', 'commit': {'oid': '1db7d1a74c8905b9b99b5580dae11b2ae7744456'}}]
INFO:root:PR pull request #11 can't be approved by kwankyu since others reqest changes
```


By https://github.com/sagemath/sage/pull/36177#issuecomment-1704022893 this could be because you have less permissions than the bot. But from the list of reviews it is not reasonable that the review with id `PRR_kwDOI72C3M5iF9Zp` is prior to the review `PRR_kwDOI72C3M5iGK1X`. Furthermore, the *check icon* behind your review is green and not gray, indicating that you have sufficient permission. I don't understand this. @tobiasdiez can you explain?  

How shall we proceed? I suggest that I first fix these two issues and your rephrasing suggestions. Explicitly:

Concerning 1. I will replace the check for membership in the Triage team by a check that a review of the actor has `authorAssociation` in (`MEMBER`, `CONTRIBUTOR`, `COLLABORATOR`). This means that the actor made at least one contribution to Sage. 

Concerning 2. I will completely ignore the `reviewDecision`, now. Furthermore, I will change that only the latest proper review since the last commit will be taken into consideration.

Afterwards we should repeat the tests above. If there will still be inconvenient restrictions left which are expected from the code then we can discuss if they should be dropped.

Concerning your suggestion to remove all restrictions on adding `s: positive review`: If we do that, I think we should at least post a hint comment if the situation is unclear. For example, if there are no restrictions an author of a PR could set the label without any review being done. Has this been possible in Trac, as well? I've never tried it.

**Comment by tobiasdiez** [comment]
Are you filtering out the bot when looking at the reviews? 

It should be okay to prevent setting the "positive review" label if there are changes requested. Admins can invalidate a review, so it's always possible to overwrite it and then proceed as normal.

**Comment by soehms** [comment]
> Are you filtering out the bot when looking at the reviews?
>

Not in general. Only when the authors tries to set `s: positve review`. Than there sould be reviews of oher real persons.
 
> It should be okay to prevent setting the "positive review" label if there are changes requested. Admins can invalidate a review, so it's always possible to overwrite it and then proceed as normal.

If I've implemented the above suggestions then I think it should work without the help of an admin.

**Comment by tobiasdiez** [comment]
In my opinion it's a good thing that you cannot set it to positive review if there is a review requesting changes. Github has a similar feature in the branch protection rules.

**Comment by soehms** [comment]
> In my opinion it's a good thing that you cannot set it to positive review if there is a review requesting changes. Github has a similar feature in the branch protection rules.

Sorry if I was unclear about that. After the changes proposed in https://github.com/soehms/sage/pull/11#issuecomment-1739662270 this will still be the case unless there is a commit or approval that happend after the changes have been requested. This has been my intention from the beginning but unfortunately that didn't work in the above tests.

One point was the failure of authentication as a Triage member when the user approves the PR (see issue 1 above). AFAIK any GitHub user can do that. So in order to not increase the set of people who can set the `s: positive review` label I implemented this check. My proposal in https://github.com/soehms/sage/pull/11#issuecomment-1739662270 whould weaken that.

Do you know, if there is a possibility to avoid this weakening? For example by login in the bot into some virtual account that is a member of the Triage team?

**Comment by tobiasdiez** [comment]
> Tip: Personal accounts are intended for humans, but you can create accounts to automate activity on GitHub. This type of account is called a machine user. For example, you can create a machine user account to automate continuous integration (CI) workflows.

You can create a new completely new "sage-bot" account (just as you create a normal account), then we can add it to whatever team it needs to be in. But you need to add a way to pass the personal token of that account to your script. I let you decide if its worth the overhead ;-)

**Comment by soehms** [comment]
> > Tip: Personal accounts are intended for humans, but you can create accounts to automate activity on GitHub. This type of account is called a machine user. For example, you can create a machine user account to automate continuous integration (CI) workflows.
> 
> You can create a new completely new "sage-bot" account (just as you create a normal account), then we can add it to whatever team it needs to be in. But you need to add a way to pass the personal token of that account to your script. I let you decide if its worth the overhead ;-)

Thanks! At the moment I don't think the overhaed is worth it.

**Comment by soehms** [comment]
The latest commit contains the changes I suggested in https://github.com/soehms/sage/pull/11#issuecomment-1739662270.

Note that the changes to issue 1 are not relevant for activating the `labeled`-trigger. They apply if the `submitted`-trigger is enabled and only affect the approval of a PR via the GitHub functionality. More precisely, it will add the `s: positive review` label for authorized users. The changes affect the meaning of *authorized*. 

To do this, I have implemented a hybrid version of the suggestions in https://github.com/soehms/sage/pull/11#issuecomment-1739662270 and https://github.com/soehms/sage/pull/11#issuecomment-1740419380. This means that it is prepared to use a separate bot account that is a member of the SageMath organization. The previously proposed changes will be implemented as a fallback if a token is not provided for such a bot.

The meaning of *authorized* differs as follows:

1. If a token named `SYNC_LABELS_BOT_TOKEN` for a specific bot account is provide in the secrets of the `sagemath/sage` repository, Triage team members are authorized (at the moment 110 users). A good example for such a bot account is [sagemathadmins](https://github.com/sagemathadmins), which is used for Sage's Docker Hub images. Maybe we can use it for our purpose, too .

2. If no such token is provided, pubic members of the SageMath organization are authorized (at the moment 45 of 495 members).

@kwankyu Can you test it again? Currently, I have my private account token set as `SYNC_LABELS_BOT_TOKEN` in my fork. Therefore, I assume that if you set a positive review, the bot (i.e. me) won't be able to approve my PR. On the other hand, if you approve the PR, the bot should set the label. ~Sorry, this is not working yet. I think I have to update the `sync_labes.yml` in the `sync_labels_fixes_part2` branch first~(yes this helped). 

If this test goes as expected, I will remove the `SYNC_LABELS_BOT_TOKEN` secret from my repository so that `github-action` will be the bot again. You should then repeat the test. Now I expect that setting positive review should give an approval of the `github-action[bot]`. On the other hand, a PR approval will not set the label unless you make your membership public.

**Comment by soehms** [comment]
Label Sync Hint: You don't need to remove status labels any more. You'd better just add the label which replaces it

**Review by kwankyu — CHANGES_REQUESTED** [review]
Reverting approval.

**Review by kwankyu — APPROVED** [review]
Approval again

**Review by kwankyu — CHANGES_REQUESTED** [review]
Reverting again.

**Comment by soehms** [comment]
Label Sync Warning: Label *s: needs review* can not be added, since there are unresolved reviews

**Review by kwankyu — APPROVED** [review]
Approving again.

**Comment by soehms** [comment]
Label Sync Warning: Label *s: needs review* can not be added, since there are unresolved reviews

**Comment by soehms** [comment]
Label Sync Hint: You don't need to remove status labels any more. You'd better just add the label which replaces it

**Comment by kwankyu** [comment]
One anomaly is that a label removed is not removed in the "Labels" pane. I needed to reload this webpage to see changed "Labels".

**Comment by soehms** [comment]
Many Thanks! 

> One anomaly is that a label removed is not removed in the "Labels" pane. I needed to reload this webpage to see changed "Labels".

Yes, I've observed this, too. But I think this is a bug in the GH web-interface.

I've removed the secret, now. Can you do the test again?

**Review by kwankyu — CHANGES_REQUESTED** [review]
Requesting changes

**Review by kwankyu — APPROVED** [review]
Approving

**Review by kwankyu — CHANGES_REQUESTED** [review]
Requesting changes again

**Review by kwankyu — APPROVED** [review]
Approving again

**Comment by kwankyu** [comment]
I cannot add "needs review" label because the bot "requested changes" (instead of me).

**Comment by soehms** [comment]
> I cannot add "needs review" label because the bot "requested changes" (instead of me).

The reason for this is that there was no further push to the branch after the `requested changes`. Usually you change from *needs work* to *needs review* after you pushed the correction to the ticket (which will happen automatically once the *synchronized* trigger is enabled). The bot is now waiting for such a push.

The scenario you tested would be a case where the reviewer who requested the changes wants to revert his decision. I agree that this is blocked at the moment. As an owner I can dismiss the review of `github-action` but you can only Re-request the review, which does not change the state which is visible to the bot so far.

For now, I'm fixing that the bot's reviews that contain the actor's login name in the body (this is now only the case for request changes) are ignored when *needs review* is set. I'll check if there's a way to dismiss or delete the bot's reviews.

If a reviewer accidentally sets a *positive review*, he will still need to request changes to revert his decision, as it is not possible any more to recover which bot review is the one he initiated.

**Comment by kwankyu** [comment]
OK.

> > One anomaly is that a label removed is not removed in the "Labels" pane. I needed to reload this webpage to see changed "Labels".
> 
> Yes, I've observed this, too. But I think this is a bug in the GH web-interface.

I am not sure. Sometimes it works, sometimes not. You may investigate in what cases it doesn't work. If this persists, this could be a show-stopper, as bot's automatic labelling leads to confusion.

Anyway, if other things are working as you expect. I don't object to experiment in the battle field again.

**Comment by kwankyu** [comment]
It worked now. I see one label.

**Comment by kwankyu** [comment]
It didn't work now. I see two labels.

**Comment by kwankyu** [comment]
Ah! After adding the above comment, the removed label disappeared. Now I see one label.

**Comment by kwankyu** [comment]
Please fix: "can not" ---> "cannot".

**Comment by kwankyu** [comment]
Also I suggest:

"Please use the GitHub review functionality" -> "Please use GitHub's review system"

**Review by kwankyu — APPROVED** [review]
Nice.

**Comment by kwankyu** [comment]
I guess people would complain that bot forbids manually adding "positive view" though...

**Comment by soehms** [comment]
Thank you for these insightful tests!

> Ah! After adding the above comment, the removed label disappeared. Now I see one label.

Good hint! Also editing a comment causes a refresh. Once these changes are merged I will send a bug report to GitHub.

> I guess people would complain that bot forbids manually adding "positive view" though...

In this case it was not intended. I fix this in the current commit. Anyway, you convinced me that removing the label might be too restrictive in many cases. Therefore, I now refrain from removing it, except if the author tries to approve his own PR.

> "Please use the GitHub review functionality" -> "Please use GitHub's review system"

I completely rephrase these comments (taking care of your suggestions) due to the fact that they are not a rejections any more.

Furthermore, I implement a dismissal of the bot's stale reviews. Unfortunately this is not possible without a message text which will increase the verbosity again (but I'm surprised that the bot posted twice after I pushed the new commit). But if we don't do it, there would persist bot reviews requesting changes (or approving) even though, the PR is on *needs review*


Can you test again?

**Comment by soehms** [comment]
> but I'm surprised that the bot posted twice after I pushed the new commit

There have been 8 dismissals, 6 with *changes requested* and 2 with *approved*. So I guess that for each type there will be one message:

```
DEBUG:root:Bot review with node_id PRR_kwDOI72C3M5iFiYo has id 1645618728
DEBUG:root:Execute command: gh api -X PUT -H "Accept: application/vnd.github+json" /repos/soehms/sage/pulls/11/reviews/1645618728/dismissals -f message="New changes ready for review" -f event="DISMISS"
INFO:root:Review 1645618728 (node_id PRR_kwDOI72C3M5iFiYo, state RevState.changes_requested) on PR pull request #11 dismissed

DEBUG:root:Bot review with node_id PRR_kwDOI72C3M5iF8xa has id 1645726810
DEBUG:root:Execute command: gh api -X PUT -H "Accept: application/vnd.github+json" /repos/soehms/sage/pulls/11/reviews/1645726810/dismissals -f message="New changes ready for review" -f event="DISMISS"
INFO:root:Review 1645726810 (node_id PRR_kwDOI72C3M5iF8xa, state RevState.approved) on PR pull request #11 dismissed

DEBUG:root:Bot review with node_id PRR_kwDOI72C3M5iF9Zp has id 1645729385
DEBUG:root:Execute command: gh api -X PUT -H "Accept: application/vnd.github+json" /repos/soehms/sage/pulls/11/reviews/1645729385/dismissals -f message="New changes ready for review" -f event="DISMISS"
INFO:root:Review 1645729385 (node_id PRR_kwDOI72C3M5iF9Zp, state RevState.changes_requested) on PR pull request #11 dismissed

DEBUG:root:Bot review with node_id PRR_kwDOI72C3M5i4d1w has id 1658969456
DEBUG:root:Execute command: gh api -X PUT -H "Accept: application/vnd.github+json" /repos/soehms/sage/pulls/11/reviews/1658969456/dismissals -f message="New changes ready for review" -f event="DISMISS"
INFO:root:Review 1658969456 (node_id PRR_kwDOI72C3M5i4d1w, state RevState.changes_requested) on PR pull request #11 dismissed

DEBUG:root:Bot review with node_id PRR_kwDOI72C3M5i4haU has id 1658984084
DEBUG:root:Execute command: gh api -X PUT -H "Accept: application/vnd.github+json" /repos/soehms/sage/pulls/11/reviews/1658984084/dismissals -f message="New changes ready for review" -f event="DISMISS"
INFO:root:Review 1658984084 (node_id PRR_kwDOI72C3M5i4haU, state RevState.changes_requested) on PR pull request #11 dismissed

DEBUG:root:Bot review with node_id PRR_kwDOI72C3M5jB4l3 has id 1661438327
DEBUG:root:Execute command: gh api -X PUT -H "Accept: application/vnd.github+json" /repos/soehms/sage/pulls/11/reviews/1661438327/dismissals -f message="New changes ready for review" -f event="DISMISS"
INFO:root:Review 1661438327 (node_id PRR_kwDOI72C3M5jB4l3, state RevState.approved) on PR pull request #11 dismissed

DEBUG:root:Bot review with node_id PRR_kwDOI72C3M5jB5fi has id 1661442018
DEBUG:root:Execute command: gh api -X PUT -H "Accept: application/vnd.github+json" /repos/soehms/sage/pulls/11/reviews/1661442018/dismissals -f message="New changes ready for review" -f event="DISMISS"
INFO:root:Review 1661442018 (node_id PRR_kwDOI72C3M5jB5fi, state RevState.changes_requested) on PR pull request #11 dismissed

DEBUG:root:Bot review with node_id PRR_kwDOI72C3M5jB9M2 has id 1661457206
DEBUG:root:Execute command: gh api -X PUT -H "Accept: application/vnd.github+json" /repos/soehms/sage/pulls/11/reviews/1661457206/dismissals -f message="New changes ready for review" -f event="DISMISS"
INFO:root:Review 1661457206 (node_id PRR_kwDOI72C3M5jB9M2, state RevState.changes_requested) on PR pull request #11 dismissed
```

**Review by kwankyu — CHANGES_REQUESTED** [review]
OK.

**Review by kwankyu — APPROVED** [review]
Approving

**Review by kwankyu — CHANGES_REQUESTED** [review]
Requesting changes.

**Comment by kwankyu** [comment]
Now there are two labels...

**Comment by kwankyu** [comment]
Now there is one label "needs info".

**Comment by kwankyu** [comment]
Comment to refresh labels.

**Comment by kwankyu** [comment]
OK. One label.

**Comment by kwankyu** [comment]
Synchronizing script failed. I added "positive review" when I have "requested changes". This is certainly an error on my side. This is a legitimate case for the script to say something like "Approve first by the review system".

**Review by kwankyu — APPROVED** [review]
Now approving

**Comment by kwankyu** [comment]
The script seems to fail because the bot "requested changes".

**Comment by kwankyu** [comment]
Now two labels are genuine.

**Comment by soehms** [comment]
> Synchronizing script failed. I added "positive review" when I have "requested changes". This is certainly an error on my side. This is a legitimate case for the script to say something like "Approve first by the review system".

> The script seems to fail because the bot "requested changes".

In both cases the reason for the failure was that I accidentally broke the code. I reduced the argument list of the method that checks whether the conflicting review was initiated by the actor himself:

```
 File "/home/runner/work/sage/sage/.github/sync_labels.py", line 552, in approve_allowed
    revs = [rev for rev in revs if not self.review_by_actor(rev)]
 File "/home/runner/work/sage/sage/.github/sync_labels.py", line 552, in <listcomp>
    revs = [rev for rev in revs if not self.review_by_actor(rev)]
TypeError: GhLabelSynchronizer.review_by_actor() takes 1 positional argument but 2 were given
```

This is now fixed! But before you test again, please let me know what you think about the following suggestion:

At the moment when the actor submits an approval, the bot sets a *positive review* if there is no review from another user requesting changes since the last commit. It is not checked whether requested reviews from other users are pending. Should I do such an exam? Of course, this is not relevant for activating the `labeled` trigger. But the sooner I do it, the better.

**Comment by kwankyu** [comment]
> At the moment when the actor submits an approval, the bot sets a _positive review_ if there is no review from another user requesting changes since the last commit. It is not checked whether requested reviews from other users are pending. Should I do such an exam? 

No. It is often the case that requested reviews are not answered.

**Review by kwankyu — CHANGES_REQUESTED** [review]
Requesting changes.

**Review by kwankyu — APPROVED** [review]
Approving

**Review by kwankyu — CHANGES_REQUESTED** [review]
Requesting changes again

**Review by kwankyu — APPROVED** [review]
Approving

**Comment by kwankyu** [comment]
"dismissed their stale review" -> "dismissed the stale review"

"@kwankyu reverts decision" -> "@kwankyu reverted decision"

and perhaps every message should end in a period.

**Comment by kwankyu** [comment]
It seems the bot behaves more smooth.

The problem of "not disappearing removed label" still persists. I am not sure if we can deploy the script before github fixes the bug.

**Comment by soehms** [comment]
>>  At the moment when the actor submits an approval, the bot sets a positive review if there is no review from another user requesting changes since the last commit. It is not checked whether requested reviews from other users are pending. Should I do such an exam?
>
> No. It is often the case that requested reviews are not answered.

Yes, but the check would make the bot's behavior more defensive. If we activate the `submitted` trigger without doing this, a user who approves one of two requested reviews will have to remove the *positive review* label that the bot would add if he wanted to leave the decision to the other reviewer. Such an action is currently not necessary.

Conversely, if we make the proposed change and the user wants the *positive review* label to be added, he will have to do it manually, but only if another review request is pending. But that is an action that he has to carry out at the moment, too.

> The problem of "not disappearing removed label" still persists. I am not sure if we can deploy the script before github fixes the bug.

My suggestion: We don't enable events until GitHub fixes the bug. But to make it easier for them to reproduce the behavior and for us/me to answer their questions, it would be desirable to have the code in one place. Therefore, I would create the bug report after the fixes made here are merged into the develop branch.

**Comment by kwankyu** [comment]
> Conversely, if we make the proposed change and the user wants the _positive review_ label to be added, he will have to do it manually, but only if another review request is pending. But that is an action that he has to carry out at the moment, too.

OK. This seems reasonable. 

> My suggestion: We don't enable events until GitHub fixes the bug. But to make it easier for them to reproduce the behavior and for us/me to answer their questions, it would be desirable to have the code in one place. Therefore, I would create the bug report after the fixes made here are merged into the develop branch.

OK.

**Comment by soehms** [comment]
> > Conversely, if we make the proposed change and the user wants the _positive review_ label to be added, he will have to do it manually, but only if another review request is pending. But that is an action that he has to carry out at the moment, too.
> 
> OK. This seems reasonable.
> 

I made the change, now. Can you test approving, again?

**Review by kwankyu — APPROVED** [review]
Approving

**Review by kwankyu — CHANGES_REQUESTED** [review]
Requesting changes

**Comment by kwankyu** [comment]
This time, when I "requested changes", the label changes were immediately effective, showing only one label.

**Review by kwankyu — APPROVED** [review]
Approving again

**Comment by kwankyu** [comment]
`kwankyu` instead of `@kwankyu` again?

**Comment by kwankyu** [comment]
Perhaps messages should end in periods.

**Comment by kwankyu** [comment]
Dummy comment to set the labels right.

**Comment by kwankyu** [comment]
At this moment, the bot's review status is in "requesting changes". Perhaps the bot should always be in "approved" state?

**Comment by kwankyu** [comment]
OK. I will use github review system.

**Comment by kwankyu** [comment]
Why this warning? This looks like the old buggy behavior...

**Review by kwankyu — CHANGES_REQUESTED** [review]
I already approved...

**Review by kwankyu — APPROVED** [review]
Approving again

**Comment by kwankyu** [comment]
???

**Comment by kwankyu** [comment]
I think removing a label manually should be allowed, unless it results in an inconsistent state.

**Comment by soehms** [comment]
> Why this warning? This looks like the old buggy behavior...

Yes! Sorry, I switched the default branch back to develop and forgot the switch it back to this branch! Now it should be o.K. again!

**Review by kwankyu — CHANGES_REQUESTED** [review]
requesting changes

**Review by kwankyu — APPROVED** [review]
approving

**Review by kwankyu — CHANGES_REQUESTED** [review]
requesting changes again

**Review by kwankyu — APPROVED** [review]
approving

**Review by kwankyu — CHANGES_REQUESTED** [review]
requesting changes again

**Review by kwankyu — APPROVED** [review]
approving late

**Review by kwankyu — APPROVED** [review]
approving

**Review by kwankyu — CHANGES_REQUESTED** [review]
requesting changes again

**Comment by kwankyu** [comment]
I am not sure if the message "dismissed the stale review because @kwankyu requested changes" is useful.

**Review by kwankyu — APPROVED** [review]
approving

**Comment by kwankyu** [comment]
The bot feels gentle now overall. I feel that the bot is supportive and not overly restrictive. I like it.

**Comment by kwankyu** [comment]
`@kwankyu reverts decision` --> `@kwankyu reverted decision` 

Or perhaps all messages (after label changes) can be the same `@kwankyu changed the review state.`

**Comment by kwankyu** [comment]
This is an old question: Which do you prefer "review state" or "review status"? 

I was promoting "status label" because I thought that there is a hierarchy: "needs info -> needs work -> needs review -> positive review". Now I won't insist any more because I value consistency more. So whichever you prefer, I am willing to follow and want to update the developer guide with consistent terminology "state label" or "status label" depending on your decision.

**Comment by soehms** [comment]
> I am not sure if the message "dismissed the stale review because @kwankyu requested changes" is useful.

I agree. But unfortunately it is unavoidable when stale reviews are dismissed. The only thing I can change (but not omit) is the text in the box ("because @kwankyu requested changes").

> The bot feels gentle now overall. I feel that the bot is supportive and not overly restrictive. I like it.

Thanks!

> @kwankyu reverts decision --> @kwankyu reverted decision
>
> Or perhaps all messages (after label changes) can be the same @kwankyu changed the review state.

I would prefer different messages because then it becomes clear where they are coming from.

> This is an old question: Which do you prefer "review state" or "review status"?
> 
> I was promoting "status label" because I thought that there is a hierarchy: "needs info -> needs work -> needs review -> positive review". Now I won't insist any more because I value consistency more. So whichever you prefer, I am willing to follow and want to update the developer guide with consistent terminology "state label" or "status label" depending on your decision.

My observation is that GitHub consistently uses the term *state* (but consistency is not GitHub's strength). In Trac we were used to the term *status* (which sounds rather German to me). Therefore, one way to maintain consistency would be to use *state* for the GitHub review system and *status* for the labels inherited from Trac.

In my code I mostly used *state* for both cases, except in the log messages. All comments the bot posts use *status*. Personally, I would prefer a distinguished consistency as described above. If you don't like that, I would adopt the GitHub convention as Trac will disappear from our minds over time.

**Comment by kwankyu** [comment]
> > I am not sure if the message "dismissed the stale review because @kwankyu requested changes" is useful.
> 
> I agree. But unfortunately it is unavoidable when stale reviews are dismissed. The only thing I can change (but not omit) is the text in the box ("because @kwankyu requested changes").

Then please make the message a complete sentence instead of starting with "because ...".

> I would prefer different messages because then it becomes clear where they are coming from.

OK.

> My observation is that GitHub consistently uses the term _state_ (but consistency is not GitHub's strength). In Trac we were used to the term _status_ (which sounds rather German to me). 

Sounds Latin to me :-)

> Therefore, one way to maintain consistency would be to use _state_ for the GitHub review system and _status_ for the labels inherited from Trac.

I like this too. This would be most comfortable to the most people.

**Comment by soehms** [comment]
> Then please make the message a complete sentence instead of starting with "because ...".

Done.

> > Therefore, one way to maintain consistency would be to use _state_ for the GitHub review system and _status_ for the labels inherited from Trac.
> 
> I like this too. This would be most comfortable to the most people.

Now, code and its output use the terms in this sense.

**Review by kwankyu — CHANGES_REQUESTED** [review]
requesting changes

**Review by kwankyu — APPROVED** [review]
approving

**Review by kwankyu — APPROVED** [review]
approving again

**Review by kwankyu — CHANGES_REQUESTED** [review]
requesting changes.

**Review by kwankyu — APPROVED** [review]
approving late

**Comment by kwankyu** [comment]
Suggestion
```
Label Sync Hint: You don't need to remove status labels any more. You'd better just add the label which replaces it
```
--->
```
You don't need to remove status labels any more. You'd better just add the label which replaces it.
```
Note the period at the end.

**Comment by kwankyu** [comment]
Otherwise I am happy with it.

**Comment by soehms** [comment]
> Suggestion
> 
> ```
> Label Sync Hint: You don't need to remove status labels any more. You'd better just add the label which replaces it
> ```
> 
> --->
> 
> ```
> You don't need to remove status labels any more. You'd better just add the label which replaces it.
> ```
> 
> Note the period at the end.

Done!

**Pull request merged**
